package com.yana.movies.entities;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "movies")
public class Movie {
@DynamoDBHashKey
@DynamoDBAutoGeneratedKey
    String id;
@DynamoDBAttribute
    String movieName;
@DynamoDBAttribute
    String description;

}
